inherit_from:
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - "bin/**/*"
    - "db/migrate/**/*"
    - "db/data/migrate/**/*"
    - "db/schema.rb"
    - "config/**/*"
    - "script/**/*"

require:
  - rubocop-rails

Rails/UnknownEnv:
  Environments:
    - production
    - staging
    - development
    - test

Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 12

Metrics/MethodLength:
  Max: 32

Metrics/ClassLength:
  Max: 200

Metrics/AbcSize:
  Max: 69

Metrics/BlockLength:
  Max: 25
  Exclude:
    - "spec/**/*.rb"
    - "lib/tasks/*.rake"

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/BlockComments:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: false

Rails/HasAndBelongsToMany:
  Exclude:
    - "app/models/role.rb" # This instance was auto generated.

Rails/Output:
  Exclude:
    - "db/seeds.rb"

Rails/FilePath:
  EnforcedStyle: arguments

# Don't worry about this in the spec helper
Style/MixinUsage:
  Exclude:
    - "spec/support/features/warden_helpers.rb"

# We need to mark the CMS page bodies as html safe to render them properly
Rails/OutputSafety:
  Exclude:
    - "app/controllers/admin/cms_pages_controller.rb"
    - "app/controllers/cms_pages_controller.rb"
