default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] %>
  database: railsapp_<%= Rails.env %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

staging:
  <<: *default

production:
  <<: *default

development:
  <<: *default
  database: cpldl_development

test:
  <<: *default
  database: cpldl_test
